#!/bin/bash

dockerize \
  -template /scaffold/scaffold.ini:/usr/local/etc/php/conf.d/scaffold.ini \
  -template /scaffold/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf \
  -template /scaffold/default.conf:/etc/nginx/conf.d/default.conf

/scaffold/30-tune-worker-processes.sh

exec su-exec ${ASUSER} "${@}"
