#!/bin/bash

dockerize \
  -template /scaffold/scaffold.ini:/usr/local/etc/php/conf.d/scaffold.ini \
  -template /scaffold/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf

[[ "${@}" == 'php-fpm' ]] && exec "${@}" || exec su-exec ${ASUSER} "${@}"
