name: Deploy
on: [push, workflow_dispatch]
env:
  IMAGE_NAME: scaffold-php8
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      parallel: 4
      matrix:
        type: [fpm-dev] #, fpm-prod, nginx-fpm-dev, nginx-fpm-prod, quality]

    steps:
      - { name: Checkout code, uses: actions/checkout@v3.1.0 }

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.ref == refs/heads/main && github.repository == ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}
        with: { username: "${{ secrets.DOCKERHUB_USERNAME }}", password: "${{ secrets.DOCKERHUB_PASSWORD }}" }

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          load: true
          context: ${{ matrix.type }}
          tags: thiagobraga/${IMAGE_NAME}:${{ matrix.type }}

      - name: Test images
        run: |
          echo "export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          ./test.build.sh ${{ matrix.type }}
          ./test.run.sh ${{ matrix.type }}

      - name: Build and push
        uses: docker/build-push-action@v3
        if: github.ref == refs/heads/main && github.repository == ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}
        with:
          push: true
          context: ${{ matrix.type }}
          tags: thiagobraga/${IMAGE_NAME}:${{ matrix.type }}
