name: Update Docker Hub image description
on:
  push:
    branches: [main]
    paths: [README.md, .github/workflows/docker-description.yml]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Sync Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: thiagobraga/scaffold-php8
          short-description: ${{ github.event.repository.description }}
